services:
  dst-server:
    image: jamesits/dst-server:latest
    container_name: dst-server
    restart: on-failure:5
    network_mode: host
    environment:
      DST_SERVER_ARCH: amd64
    volumes:
      - ./data:/data
    stop_grace_period: 6m
